service: serverless
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  memorySize: 128
  stage: ${opt:stage, 'dev'}

functions:
  createUser:
    handler: src/handlers/user/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST
  login:
    handler: src/handlers/auth/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: POST
  refresh:
    handler: src/handlers/auth/refresh.handler
    events:
      - httpApi:
          path: /auth/refresh
          method: POST
