service: serverless
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-middleware

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  memorySize: 128
  stage: ${opt:stage, 'dev'}

functions:
  # /users
  createUser:
    handler: src/handlers/user/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST
  # /auth
  login:
    handler: src/handlers/auth/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: POST
  refresh:
    handler: src/handlers/auth/refresh.handler
    events:
      - httpApi:
          path: /auth/refresh
          method: POST
  # /account
  sendVerificationEmail:
    handler: src/handlers/account/sendVerificationEmail.handler
    events:
      - httpApi:
          path: /account/verification
          method: POST
  verifyEmailToken:
    handler: src/handlers/account/verifyEmailToken.handler
    events:
      - httpApi:
          path: /account/verification/{verificationToken}
          method: GET
  resetPassword:
    handler: src/handlers/account/resetPassword.handler
    events:
      - httpApi:
          path: /account/resetPassword
          method: POST
  changePassword:
    middleware:
      pre:
        - src/handlers/auth/authenticate.handler
    handler: src/handlers/account/changePassword.handler
    events:
      - httpApi:
          path: /account/changePassword
          method: POST
  # /clubs
  createClub:
    middleware:
      pre:
        - src/handlers/auth/authenticate.handler
    handler: src/handlers/club/createClub.handler
    events:
      - httpApi:
          path: /clubs
          method: POST
