name: Testing pipeline

on: [push, pull_request]

jobs:
  testing_pipeline:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19.6.0"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: unit test
        run: npm run test
      - name: integration test
        run: npm run test:integration
